// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzLZVJP7XkskaZiNPsr6-5LaQDzjGhTQI',
    appId: '1:487147307718:web:a0233e6aef2d9d7c24cdc7',
    messagingSenderId: '487147307718',
    projectId: 'chatpro-47c5c',
    authDomain: 'chatpro-47c5c.firebaseapp.com',
    storageBucket: 'chatpro-47c5c.firebasestorage.app',
    measurementId: 'G-HS283BV59N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7AyKNLgr-L51wCLYTCRLgx4cT6LxWDzQ',
    appId: '1:487147307718:android:7efc491fee88c79f24cdc7',
    messagingSenderId: '487147307718',
    projectId: 'chatpro-47c5c',
    storageBucket: 'chatpro-47c5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyIKJyvwebl5tST9upFc1H9cDYeGpBgIM',
    appId: '1:487147307718:ios:8149ecaa7e90c0a524cdc7',
    messagingSenderId: '487147307718',
    projectId: 'chatpro-47c5c',
    storageBucket: 'chatpro-47c5c.firebasestorage.app',
    iosBundleId: 'com.dev.chatMessage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyIKJyvwebl5tST9upFc1H9cDYeGpBgIM',
    appId: '1:487147307718:ios:8149ecaa7e90c0a524cdc7',
    messagingSenderId: '487147307718',
    projectId: 'chatpro-47c5c',
    storageBucket: 'chatpro-47c5c.firebasestorage.app',
    iosBundleId: 'com.dev.chatMessage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzLZVJP7XkskaZiNPsr6-5LaQDzjGhTQI',
    appId: '1:487147307718:web:899f92c54874f42824cdc7',
    messagingSenderId: '487147307718',
    projectId: 'chatpro-47c5c',
    authDomain: 'chatpro-47c5c.firebaseapp.com',
    storageBucket: 'chatpro-47c5c.firebasestorage.app',
    measurementId: 'G-Y2PSZYRYP4',
  );
}
